name: myPlugin
main: fr.piarre.myPlugin.Main
version: 1.0.0
api-version: 1.16
author: Pierre
commands:
  ss:
    description: Test command
    permission-message: You need the permission to use this command
    permission: myPlugin.ss
  mode:
    description: Test command
    permission: myPlugin.mode
  gui:
    description: Test command
    permission: myPlugin.gui
